Question 1: Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np

In [ ]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Question 2: Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [ ]:
list1=[]
for i in range(5):
  list1.append(float(input("enter a number: ")))

enter a number: 3
enter a number: 4
enter a number: 5
enter a number: 6
enter a number: 7


In [ ]:
list1

[3.0, 4.0, 5.0, 6.0, 7.0]

In [ ]:
list2=[]
for i in range(5):
  list2.append(float(input("enter a number: ")))

enter a number: 3
enter a number: 2
enter a number: 1
enter a number: 5
enter a number: 6


In [ ]:
Arr1=np.array(list1)
Arr2=np.array(list2)
Arr1

array([3., 4., 5., 6., 7.])

In [ ]:
print(np.concatenate((Arr1,Arr2)))

[3. 4. 5. 6. 7. 3. 2. 1. 5. 6.]


In [ ]:
print(np.sort(np.concatenate((Arr1,Arr2))))

[1. 2. 3. 3. 4. 5. 5. 6. 6. 7.]


In [ ]:
#Write a code snippet to find the dimensions of a ndarray and its size
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('shape : ',arr.shape)
print('ndim :', arr.ndim)
arr.size

shape :  (3, 3)
ndim : 2


9

In [ ]:
# Q4. How to convert a 1D array into a 2D array? Demonstrate with the help of a c
# Hint: np.newaxis, np.expand_dims
arr2=arr[:,np.newaxis]
print('shape : ',arr2.shape)
arr2

shape :  (3, 1, 3)


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [ ]:
arr3=arr[np.newaxis,:]
print('shape : ',arr3.shape)
arr3

shape :  (1, 3, 3)


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr4=np.expand_dims(arr2,axis=0)
print(arr4.shape)
arr4

(1, 3, 1, 3)


array([[[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]]])

Q5. Consider two square numpy. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()


In [ ]:
numpy1=np.arange(9)
square_numpy1=numpy1.reshape(3,3)
square_numpy1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
numpy2=np.arange(10,19)
square_numpy2=numpy2.reshape(3,3)
square_numpy2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.vstack((square_numpy1,square_numpy2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack((square_numpy1,square_numpy2))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

Q6. How to get unique items and counts of unique items?


In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(a)
print(np.unique(a))

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique,occur_count=np.unique(a,return_counts=True)

In [ ]:
print(unique)
print(occur_count)

[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]
